1, my_project
11, settings
110, __init__.py
110, dev.py
110, prod.py
11, mainapp
110, __init__.py
110, models.py
110, views.py
111, templates
1111, mainapp
11110, base.html
11110, index.html
11, authapp
110, __init__.py
110, models.py
110, views.py
111, templates
1111, authapp
11110, base.html
11110, index.html